### ISSUE TITLE
File "./linux-kernel.def", line 44, characters 29-30: unexpected '-' (in macros)

### ISSUE THREAD

**Issue by anthezium** [aparri/memory-model#1]
Hey folks,

I'm assuming that I'm running the wrong version of herd7 (fresh from opam):
```
0 theod@beor:~/git/memory-model$ herd7 -conf linux-kernel.cfg litmus-tests/S+poonceonces.litmus 
File "./linux-kernel.def", line 44, characters 29-30: unexpected '-' (in macros)
0 theod@beor:~/git/memory-model$ herd7 -version
7.47, Rev: 532a1b6166f21e64abb9101eb6d652deef6d5111
```
This is the first occurrence of a hypen not in a comment in this file, so I'm guessing that you need a version of herd (or whatever is lexing) that is happy with hypens in identifiers.  What version of herd works?

Thanks,
Ted

**Comment by aparri** [comment]
Hi Ted,

you would need at least herd7

  7.47+7(dev), Rev: 2afd2858f1c9eabd23e6305c9d49aade3c16e2bc

(from sources: https://github.com/herd/herdtools7).

Alternatively, you could checkout the memory model at the commit which precedes

   2d5fba7782d669c6a1cc577dbc3bf507780273bb
   ("linux-kernel*: Make RCU identifiers match ASPLOS paper")

Both solutions are currently under discussion on LKML:

   https://marc.info/?l=linux-kernel&m=151821999718737&w=2

Thanks,
  Andrea

**Comment by anthezium** [comment]
Thanks Andrea!
